# =============================================
#  EUREKA-SERVER - application.properties
# =============================================

server.port=8761
spring.application.name=eureka-server

# Evita que el propio servidor se registre como cliente
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Reduce el tiempo de espera al iniciar
eureka.server.wait-time-in-ms-when-sync-empty=0

# Dashboard disponible en: http://localhost:8761
